name: Deploy Static HTML App to Azure (Staging)

on:
  workflow_dispatch:  # Manually deploy karogi jab chaho

env:
  AZURE_WEBAPP_NAME: 'yousma-static-html-0427'
  AZURE_RESOURCE_GROUP: 'yousma-rg'

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Staging Slot)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: staging     # <-- Important: slot specify kiya hua hai
          package: .
